<a href="https://colab.research.google.com/github/shifupapi/Deep-Learning-Challenge/blob/main/AlphabetSoupCharity_Optimization_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN','NAME'],axis=1)

In [3]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<100].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classificationbinning = application_df['CLASSIFICATION'].value_counts()
classificationbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = classificationbinning[classificationbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classificationbinning[classificationbinning<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns='IS_SUCCESSFUL')
y = application_df['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
hidden_nodes1=80
hidden_nodes2=30
hidden_nodes3=1


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes3, activation='relu'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4080

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6,541
Trainable params: 6,541
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 6s 5ms/step - loss: 1.2348 - accuracy: 0.6802 - val_loss: 0.9722 - val_accuracy: 0.7085
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.8489 - accuracy: 0.7159 - val_loss: 0.7739 - val_accuracy: 0.7292
Epoch 3/100
684/684 [==============================] - 1s 2ms/step - loss: 0.8218 - accuracy: 0.7204 - val_loss: 0.7931 - val_accuracy: 0.7292
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.8320 - accuracy: 0.7180 - val_loss: 0.7533 - val_accuracy: 0.7225
Epoch 5/100
684/684 [==============================] - 2s 2ms/step - loss: 0.7615 - accuracy: 0.7161 - val_loss: 0.6822 - val_accuracy: 0.7248
Epoch 6/100
684/684 [==============================] - 1s 1ms/step - loss: 0.7071 - accuracy: 0.7238 - val_loss: 0.7828 - val_accuracy: 0.7137
Epoch 7/100
684/684 [==============================] - 1s 1ms/step - loss: 0.7436 - accuracy: 0.7137 - val_loss: 0.6626 - val_accuracy: 0.7139
Epoch 8/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6902 - accuracy: 0.7267 - val_loss: 0.6586 - val_accuracy: 0.7328
Epoch 9/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6978 - accuracy: 0.7202 - val_loss: 0.6977 - val_accuracy: 0.7318
Epoch 10/100
684/684 [==============================] - 1s 1ms/step - loss: 0.7075 - accuracy: 0.7212 - val_loss: 0.7008 - val_accuracy: 0.7274
Epoch 11/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6919 - accuracy: 0.7239 - val_loss: 0.6884 - val_accuracy: 0.7308
Epoch 12/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6987 - accuracy: 0.7292 - val_loss: 0.7411 - val_accuracy: 0.7245
Epoch 13/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6893 - accuracy: 0.7258 - val_loss: 0.6472 - val_accuracy: 0.7344
Epoch 14/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6670 - accuracy: 0.7288 - val_loss: 0.6531 - val_accuracy: 0.7150
Epoch 15/100
684/684 [==============================] - 1s 2ms/step - loss: 0.6986 - accuracy: 0.7238 - val_loss: 0.7108 - val_accuracy: 0.7297
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.6953 - accuracy: 0.7266 - val_loss: 0.6779 - val_accuracy: 0.7261
Epoch 17/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6902 - accuracy: 0.7254 - val_loss: 0.7006 - val_accuracy: 0.7305
Epoch 18/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6872 - accuracy: 0.7219 - val_loss: 0.6629 - val_accuracy: 0.7326
Epoch 19/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6541 - accuracy: 0.7259 - val_loss: 0.6312 - val_accuracy: 0.7334
Epoch 20/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6154 - accuracy: 0.7281 - val_loss: 0.6120 - val_accuracy: 0.7346
Epoch 21/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6156 - accuracy: 0.7258 - val_loss: 0.6289 - val_accuracy: 0.7269
Epoch 22/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6163 - accuracy: 0.7279 - val_loss: 0.6127 - val_accuracy: 0.7354
Epoch 23/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6121 - accuracy: 0.7278 - val_loss: 0.6225 - val_accuracy: 0.7131
Epoch 24/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5982 - accuracy: 0.7247 - val_loss: 0.5802 - val_accuracy: 0.7365
Epoch 25/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5984 - accuracy: 0.7261 - val_loss: 0.6150 - val_accuracy: 0.7354
Epoch 26/100
684/684 [==============================] - 1s 1ms/step - loss: 0.6077 - accuracy: 0.7268 - val_loss: 0.5766 - val_accuracy: 0.7217
Epoch 27/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5747 - accuracy: 0.7287 - val_loss: 0.5673 - val_accuracy: 0.7339
Epoch 28/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5754 - accuracy: 0.7318 - val_loss: 0.5755 - val_accuracy: 0.7354
Epoch 29/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5828 - accuracy: 0.7279 - val_loss: 0.5770 - val_accuracy: 0.7352
Epoch 30/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5714 - accuracy: 0.7326 - val_loss: 0.5951 - val_accuracy: 0.7362
Epoch 31/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5820 - accuracy: 0.7313 - val_loss: 0.5742 - val_accuracy: 0.7357
Epoch 32/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5946 - accuracy: 0.7187 - val_loss: 0.5811 - val_accuracy: 0.7297
Epoch 33/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5779 - accuracy: 0.7296 - val_loss: 0.5764 - val_accuracy: 0.7370
Epoch 34/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5719 - accuracy: 0.7302 - val_loss: 0.5726 - val_accuracy: 0.7375
Epoch 35/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5762 - accuracy: 0.7318 - val_loss: 0.5662 - val_accuracy: 0.7297
Epoch 36/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5726 - accuracy: 0.7274 - val_loss: 0.5782 - val_accuracy: 0.7346
Epoch 37/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5875 - accuracy: 0.7289 - val_loss: 0.6012 - val_accuracy: 0.7321
Epoch 38/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5700 - accuracy: 0.7317 - val_loss: 0.5752 - val_accuracy: 0.7269
Epoch 39/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7319 - val_loss: 0.5677 - val_accuracy: 0.7346
Epoch 40/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5926 - accuracy: 0.7282 - val_loss: 0.6004 - val_accuracy: 0.7038
Epoch 41/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5830 - accuracy: 0.7257 - val_loss: 0.5685 - val_accuracy: 0.7344
Epoch 42/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5674 - accuracy: 0.7308 - val_loss: 0.5688 - val_accuracy: 0.7357
Epoch 43/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5722 - accuracy: 0.7318 - val_loss: 0.5616 - val_accuracy: 0.7357
Epoch 44/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5691 - accuracy: 0.7323 - val_loss: 0.5962 - val_accuracy: 0.7357
Epoch 45/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5857 - accuracy: 0.7150 - val_loss: 0.5738 - val_accuracy: 0.7326
Epoch 46/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5870 - accuracy: 0.7303 - val_loss: 0.5810 - val_accuracy: 0.7362
Epoch 47/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5736 - accuracy: 0.7318 - val_loss: 0.5795 - val_accuracy: 0.7334
Epoch 48/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5696 - accuracy: 0.7333 - val_loss: 0.5832 - val_accuracy: 0.7321
Epoch 49/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5780 - accuracy: 0.7335 - val_loss: 0.5866 - val_accuracy: 0.7367
Epoch 50/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5777 - accuracy: 0.7342 - val_loss: 0.5686 - val_accuracy: 0.7357
Epoch 51/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5712 - accuracy: 0.7334 - val_loss: 0.5835 - val_accuracy: 0.7378
Epoch 52/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5876 - accuracy: 0.7312 - val_loss: 0.5967 - val_accuracy: 0.7313
Epoch 53/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5708 - accuracy: 0.7308 - val_loss: 0.5691 - val_accuracy: 0.7336
Epoch 54/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5856 - accuracy: 0.7328 - val_loss: 0.5917 - val_accuracy: 0.7362
Epoch 55/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5760 - accuracy: 0.7321 - val_loss: 0.5678 - val_accuracy: 0.7393
Epoch 56/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5633 - accuracy: 0.7345 - val_loss: 0.5702 - val_accuracy: 0.7367
Epoch 57/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5681 - accuracy: 0.7332 - val_loss: 0.5698 - val_accuracy: 0.7375
Epoch 58/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5633 - accuracy: 0.7337 - val_loss: 0.5806 - val_accuracy: 0.7372
Epoch 59/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5711 - accuracy: 0.7319 - val_loss: 0.5816 - val_accuracy: 0.7194
Epoch 60/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5668 - accuracy: 0.7346 - val_loss: 0.5642 - val_accuracy: 0.7378
Epoch 61/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5712 - accuracy: 0.7337 - val_loss: 0.5870 - val_accuracy: 0.7336
Epoch 62/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5740 - accuracy: 0.7317 - val_loss: 0.5781 - val_accuracy: 0.7365
Epoch 63/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5666 - accuracy: 0.7335 - val_loss: 0.5906 - val_accuracy: 0.7378
Epoch 64/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7339 - val_loss: 0.5882 - val_accuracy: 0.7308
Epoch 65/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5787 - accuracy: 0.7359 - val_loss: 0.5628 - val_accuracy: 0.7380
Epoch 66/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5832 - accuracy: 0.7203 - val_loss: 0.5945 - val_accuracy: 0.7339
Epoch 67/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5687 - accuracy: 0.7337 - val_loss: 0.5884 - val_accuracy: 0.7365
Epoch 68/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5620 - accuracy: 0.7340 - val_loss: 0.5963 - val_accuracy: 0.7354
Epoch 69/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5641 - accuracy: 0.7360 - val_loss: 0.6274 - val_accuracy: 0.7274
Epoch 70/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5748 - accuracy: 0.7240 - val_loss: 0.5989 - val_accuracy: 0.7230
Epoch 71/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5767 - accuracy: 0.7293 - val_loss: 0.5996 - val_accuracy: 0.7302
Epoch 72/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5666 - accuracy: 0.7311 - val_loss: 0.5766 - val_accuracy: 0.7352
Epoch 73/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5742 - accuracy: 0.7182 - val_loss: 0.5810 - val_accuracy: 0.7359
Epoch 74/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5678 - accuracy: 0.7351 - val_loss: 0.5816 - val_accuracy: 0.7344
Epoch 75/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7338 - val_loss: 0.5877 - val_accuracy: 0.7349
Epoch 76/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5710 - accuracy: 0.7222 - val_loss: 0.5750 - val_accuracy: 0.7230
Epoch 77/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7309 - val_loss: 0.5695 - val_accuracy: 0.7326
Epoch 78/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7351 - val_loss: 0.5767 - val_accuracy: 0.7341
Epoch 79/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5702 - accuracy: 0.7149 - val_loss: 0.5961 - val_accuracy: 0.7025
Epoch 80/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5682 - accuracy: 0.7296 - val_loss: 0.5758 - val_accuracy: 0.7302
Epoch 81/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5667 - accuracy: 0.7334 - val_loss: 0.5632 - val_accuracy: 0.7375
Epoch 82/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5572 - accuracy: 0.7321 - val_loss: 0.5532 - val_accuracy: 0.7346
Epoch 83/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7349 - val_loss: 0.5747 - val_accuracy: 0.7362
Epoch 84/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5691 - accuracy: 0.7320 - val_loss: 0.6230 - val_accuracy: 0.7359
Epoch 85/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5680 - accuracy: 0.7309 - val_loss: 0.5807 - val_accuracy: 0.7326
Epoch 86/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5737 - accuracy: 0.7330 - val_loss: 0.6235 - val_accuracy: 0.7264
Epoch 87/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5867 - accuracy: 0.7201 - val_loss: 0.5820 - val_accuracy: 0.7315
Epoch 88/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7311 - val_loss: 0.5779 - val_accuracy: 0.7336
Epoch 89/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5598 - accuracy: 0.7301 - val_loss: 0.5790 - val_accuracy: 0.7326
Epoch 90/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5555 - accuracy: 0.7322 - val_loss: 0.5692 - val_accuracy: 0.7341
Epoch 91/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5607 - accuracy: 0.7333 - val_loss: 0.5712 - val_accuracy: 0.7357
Epoch 92/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5598 - accuracy: 0.7327 - val_loss: 0.5950 - val_accuracy: 0.7375
Epoch 93/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5587 - accuracy: 0.7344 - val_loss: 0.6048 - val_accuracy: 0.7056
Epoch 94/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5692 - accuracy: 0.7314 - val_loss: 0.5768 - val_accuracy: 0.7370
Epoch 95/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7350 - val_loss: 0.5720 - val_accuracy: 0.7359
Epoch 96/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5703 - accuracy: 0.7276 - val_loss: 0.5731 - val_accuracy: 0.7313
Epoch 97/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5663 - accuracy: 0.7358 - val_loss: 0.5730 - val_accuracy: 0.7354
Epoch 98/100
684/684 [==============================] - 1s 1ms/step - loss: 0.5622 - accuracy: 0.7355 - val_loss: 0.5806 - val_accuracy: 0.7403
Epoch 99/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7361 - val_loss: 0.6311 - val_accuracy: 0.7321
Epoch 100/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5825 - accuracy: 0.7355 - val_loss: 0.6229 - val_accuracy: 0.7375

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6250 - accuracy: 0.7326 - 227ms/epoch - 847us/step
Loss: 0.6249729990959167, Accuracy: 0.7325947284698486

In [16]:
# Export our model to HDF5 file
nn.save('../AlphabetSoupCharity_Optimization1.h5')