<a href="https://colab.research.google.com/github/shifupapi/Deep-Learning-Challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [15]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [16]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN'])

In [17]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [19]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['NAME'].value_counts()
counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [22]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<10].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [23]:
# Look at CLASSIFICATION value counts for binning
classificationbinning = application_df['CLASSIFICATION'].value_counts()
classificationbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [24]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = classificationbinning[classificationbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [25]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classificationbinning[classificationbinning<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [26]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,NAME_13TH BOMB SQUADRON ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE

# Second hidden layer
#  YOUR CODE GOES HERE

# Output layer
#  YOUR CODE GOES HERE

# Check the structure of the model
nn.summary()

WARNING:tensorflow:From Z:\Travis\anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3520
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE

WARNING:tensorflow:From Z:\Travis\anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [ ]:
# Train the model
#  YOUR CODE GOES HERE

Epoch 1/100
25724/25724 [==============================] - 2s 80us/sample - loss: 0.5700 - acc: 0.7234
Epoch 2/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5556 - acc: 0.7294
Epoch 3/100
25724/25724 [==============================] - 1s 43us/sample - loss: 0.5529 - acc: 0.7304
Epoch 4/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5514 - acc: 0.7318
Epoch 5/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5495 - acc: 0.7322
Epoch 6/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5488 - acc: 0.7330
Epoch 7/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5482 - acc: 0.7335
Epoch 8/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5475 - acc: 0.7326
Epoch 9/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5468 - acc: 0.73491s - lo
Epoch 10/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5465 - acc: 0.7350
Epoch 11/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5459 - acc: 0.7345
Epoch 12/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5456 - acc: 0.7362
Epoch 13/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5458 - acc: 0.7339
Epoch 14/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5450 - acc: 0.7361
Epoch 15/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5447 - acc: 0.7353
Epoch 16/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5444 - acc: 0.7356
Epoch 17/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5440 - acc: 0.7358
Epoch 18/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5442 - acc: 0.7367
Epoch 19/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5436 - acc: 0.7360
Epoch 20/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5435 - acc: 0.7365
Epoch 21/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5426 - acc: 0.7377
Epoch 22/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5429 - acc: 0.7367
Epoch 23/100
25724/25724 [==============================] - 1s 42us/sample - loss: 0.5428 - acc: 0.7382
Epoch 24/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5425 - acc: 0.7376
Epoch 25/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5421 - acc: 0.7379
Epoch 26/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5419 - acc: 0.7382
Epoch 27/100
25724/25724 [==============================] - 1s 56us/sample - loss: 0.5415 - acc: 0.7384
Epoch 28/100
25724/25724 [==============================] - 2s 67us/sample - loss: 0.5418 - acc: 0.7381
Epoch 29/100
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5415 - acc: 0.7381
Epoch 30/100
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5410 - acc: 0.7382
Epoch 31/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5414 - acc: 0.7381
Epoch 32/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5407 - acc: 0.7388
Epoch 33/100
25724/25724 [==============================] - 1s 44us/sample - loss: 0.5412 - acc: 0.7374
Epoch 34/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5405 - acc: 0.7383
Epoch 35/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5405 - acc: 0.7388
Epoch 36/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5405 - acc: 0.7384
Epoch 37/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5403 - acc: 0.7379
Epoch 38/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5401 - acc: 0.7392
Epoch 39/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5405 - acc: 0.7387
Epoch 40/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5399 - acc: 0.7390
Epoch 41/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5395 - acc: 0.7394
Epoch 42/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5399 - acc: 0.7391
Epoch 43/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5396 - acc: 0.7389
Epoch 44/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5398 - acc: 0.7397
Epoch 45/100
25724/25724 [==============================] - 1s 45us/sample - loss: 0.5395 - acc: 0.7400
Epoch 46/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5389 - acc: 0.7391
Epoch 47/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5391 - acc: 0.7393
Epoch 48/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5390 - acc: 0.7383
Epoch 49/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5391 - acc: 0.7390
Epoch 50/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5387 - acc: 0.7402
Epoch 51/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5388 - acc: 0.7393
Epoch 52/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5389 - acc: 0.7393
Epoch 53/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5387 - acc: 0.7394
Epoch 54/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5385 - acc: 0.7395
Epoch 55/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5381 - acc: 0.7394
Epoch 56/100
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5384 - acc: 0.7396
Epoch 57/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5384 - acc: 0.7392
Epoch 58/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5382 - acc: 0.7398
Epoch 59/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5382 - acc: 0.7390
Epoch 60/100
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5383 - acc: 0.7395
Epoch 61/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5380 - acc: 0.7393
Epoch 62/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5386 - acc: 0.7395
Epoch 63/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5379 - acc: 0.7397
Epoch 64/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5383 - acc: 0.7414
Epoch 65/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5376 - acc: 0.74031s
Epoch 66/100
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5378 - acc: 0.7407
Epoch 67/100
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5378 - acc: 0.7402
Epoch 68/100
25724/25724 [==============================] - 2s 68us/sample - loss: 0.5374 - acc: 0.7403
Epoch 69/100
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5376 - acc: 0.7400
Epoch 70/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5377 - acc: 0.7404
Epoch 71/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5377 - acc: 0.7402
Epoch 72/100
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5374 - acc: 0.7403
Epoch 73/100
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5375 - acc: 0.7400
Epoch 74/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5373 - acc: 0.7407
Epoch 75/100
25724/25724 [==============================] - 2s 72us/sample - loss: 0.5371 - acc: 0.7402
Epoch 76/100
25724/25724 [==============================] - 2s 66us/sample - loss: 0.5372 - acc: 0.7404
Epoch 77/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5372 - acc: 0.7399
Epoch 78/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5378 - acc: 0.7409
Epoch 79/100
25724/25724 [==============================] - 2s 70us/sample - loss: 0.5370 - acc: 0.7410
Epoch 80/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5371 - acc: 0.7402
Epoch 81/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5368 - acc: 0.7414
Epoch 82/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5366 - acc: 0.7413
Epoch 83/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5368 - acc: 0.7405
Epoch 84/100
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5367 - acc: 0.7407
Epoch 85/100
25724/25724 [==============================] - 2s 64us/sample - loss: 0.5368 - acc: 0.7404
Epoch 86/100
25724/25724 [==============================] - 2s 69us/sample - loss: 0.5365 - acc: 0.7408
Epoch 87/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5371 - acc: 0.7407
Epoch 88/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5367 - acc: 0.7410
Epoch 89/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5366 - acc: 0.7409
Epoch 90/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5365 - acc: 0.7409
Epoch 91/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5360 - acc: 0.7414
Epoch 92/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5370 - acc: 0.7406
Epoch 93/100
25724/25724 [==============================] - 1s 46us/sample - loss: 0.5365 - acc: 0.7411
Epoch 94/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5366 - acc: 0.7409
Epoch 95/100
25724/25724 [==============================] - 1s 56us/sample - loss: 0.5362 - acc: 0.7411
Epoch 96/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5361 - acc: 0.7404
Epoch 97/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5361 - acc: 0.74130s - loss: 0.5380 -
Epoch 98/100
25724/25724 [==============================] - 2s 64us/sample - loss: 0.5365 - acc: 0.7407
Epoch 99/100
25724/25724 [==============================] - 2s 80us/sample - loss: 0.5360 - acc: 0.7396
Epoch 100/100
25724/25724 [==============================] - 2s 64us/sample - loss: 0.5360 - acc: 0.7416

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE